WebApplicationDotNet/Controllers/CarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApplicationDotNet.Data;
using WebApplicationDotNet.Models;

namespace WebApplicationDotNet.Controllers
{
    [Authorize(Roles = "user")]
    public class CarController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CarController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var cars = _context.Cars.Where(c => c.UserId == userId).ToList();

            return View(cars);
        }
        [HttpGet]
        public IActionResult CreateCar() 
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var car = new Car
            {
                UserId = userId  
            };
            return View(car);
        }
        [HttpPost]
        public async Task<IActionResult> CreateCar([Bind("BrandAndModel,ManufactureDate,IsAvailable,RentalPrice,UserId")] Car car) 
        {
            if (!ModelState.IsValid)
            {
                return View(car);
            }
            try
            {
                await _context.Cars.AddAsync(car);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index)); 
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View(car); 
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditCar(int id)
        {
            var existingCar = await _context.Cars.FindAsync(id);
            if (existingCar == null) return View("NotFound");
            return View(existingCar);
        }
        [HttpPost]
        public async Task<IActionResult> EditCar(int id, [Bind("BrandAndModel,ManufactureDate,IsAvailable,RentalPrice,UserId")] Car car)
        {
            if (!ModelState.IsValid) return View(car);
            var existingCar = await _context.Cars.FindAsync(id);
            if (existingCar == null) return View("NotFound");
            try
            {
                existingCar.BrandAndModel = car.BrandAndModel;
                existingCar.ManufactureDate = car.ManufactureDate;
                existingCar.IsAvailable = car.IsAvailable;
                existingCar.RentalPrice = car.RentalPrice;
                existingCar.UserId = car.UserId;

                _context.Update(existingCar);
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View(car);
            }
        }

        public async Task<IActionResult> DeleteCar(int id)
        {
            var existingCar = await _context.Cars.FindAsync(id);
            if (existingCar == null) return View("NotFound");

            try
            {
                _context.Cars.Remove(existingCar);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View("Error");
            }
        }
    }
}

WebApplicationDotNet/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApplicationDotNet.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager) 
        {
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }
        [HttpGet]
        public IActionResult CreateRole() 
        {
            return View(new IdentityRole());
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(IdentityRole role)
        {
            await _roleManager.CreateAsync(role);
            return View(role);
        }
    }
}
    

WebApplicationDotNet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationDotNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationDotNet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationDotNet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Manage Roles</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("user"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Manage Cars</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplicationDotNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>